// src/entities/beat/beats.js
// Remove: import { licenses } from '../../data/licenses';

export const beats = [
  {
    id: 'beat1',
    name: 'Midnight Pulse',
    artist: 'Neofantasia',
    genre: 'Trap',
    bpm: 140,
    audioSrc: '/audio/midnight_pulse.mp3',
    // REMOVE: color: '#6A5ACD',
    // REMOVE: availableLicenses: [licenses[0].id, licenses[1].id],
  },
  {
    id: 'beat2',
    name: 'Dreamscape Echoes',
    artist: 'Neofantasia',
    genre: 'Lo-Fi',
    bpm: 80,
    audioSrc: '/audio/dreamscape_echoes.mp3',
    // REMOVE: color: '#00CED1',
    // REMOVE: availableLicenses: [licenses[0].id, licenses[1].id, licenses[2].id],
  },
  {
    id: 'beat3',
    name: 'Energetic Flow',
    artist: 'Neofantasia',
    genre: 'Pop',
    bpm: 128,
    audioSrc: '/audio/energetic_flow.mp3',
    // REMOVE: color: '#FF6347',
    // REMOVE: availableLicenses: [licenses[0].id, licenses[1].id],
  },
  {
    id: 'beat4',
    name: 'Mystic Groove',
    artist: 'Neofantasia',
    genre: 'R&B',
    bpm: 95,
    audioSrc: '/audio/mystic_groove.mp3',
    // REMOVE: color: '#DAA520',
    // REMOVE: availableLicenses: [licenses[0].id, licenses[1].id],
  },
  {
    id: 'beat5',
    name: 'Cosmic Drift',
    artist: 'Neofantasia',
    genre: 'Ambient',
    bpm: 60,
    audioSrc: '/audio/cosmic_drift.mp3',
    // REMOVE: color: '#8A2BE2',
    // REMOVE: availableLicenses: [licenses[0].id],
  },
  {
    id: 'beat6',
    name: 'Urban Grime',
    artist: 'Neofantasia',
    genre: 'Grime',
    bpm: 130,
    audioSrc: '/audio/urban_grime.mp3',
    // REMOVE: color: '#B22222',
    // REMOVE: availableLicenses: [licenses[0].id, licenses[1].id],
  },
  // Keep your other beats as they were originally
];